name: oop_class_flutter_template
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.1

dependencies:
  bloc: ^8.1.0
  cloud_firestore: ^4.9.0
  equatable: ^2.0.5
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: 
  intl: 
  json_annotation: ^4.7.0
  rxdart:

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  freezed: 
  json_serializable: ^6.4.0
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true
